config/routes.rb
Bicecle::Application.routes.draw do

  resources :positions
  resources :carriers do 
    member do 
      get 'positions'
    end
  end

end

app/models/carrier.rb
class Carrier < ActiveRecord::Base
  attr_accessible :active, :name, :carrierType

  has_many :positions

  def lastPosition
  	self.positions.sort{|x,y| y.created_at <=> x.created_at}.first
  end
end

app/models/position.rb
class Position < ActiveRecord::Base
  attr_accessible :carrier_id, :latitude, :longitude
  belongs_to :carrier
  def timestamp
  	return self.created_at.to_time.to_i
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/carriers_controller.rb
class CarriersController < ApplicationController
  # GET /carriers
  # GET /carriers.json
  def index
    @carriers = Carrier.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carriers.as_json(:methods=>:lastPosition,:include=>{:positions => {:methods=>:timestamp}}) }
    end
  end

  # GET /carriers/1
  # GET /carriers/1.json
  def show
    @carrier = Carrier.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @carrier }
    end
  end

  def positions
    @carrier = Carrier.find(params[:id])
    respond_to do |format|
      format.html 
      format.json { render :json => @carrier.positions }
    end
  end

  # GET /carriers/new
  # GET /carriers/new.json
  def new
    @carrier = Carrier.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @carrier }
    end
  end

  # GET /carriers/1/edit
  def edit
    @carrier = Carrier.find(params[:id])
  end

  # POST /carriers
  # POST /carriers.json
  def create
    @carrier = Carrier.new(params[:carrier])

    respond_to do |format|
      if @carrier.save
        format.html { redirect_to @carrier, notice: 'Carrier was successfully created.' }
        format.json { render json: @carrier, status: :created, location: @carrier }
      else
        format.html { render action: "new" }
        format.json { render json: @carrier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carriers/1
  # PUT /carriers/1.json
  def update
    @carrier = Carrier.find(params[:id])

    respond_to do |format|
      if @carrier.update_attributes(params[:carrier])
        format.html { redirect_to @carrier, notice: 'Carrier was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @carrier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carriers/1
  # DELETE /carriers/1.json
  def destroy
    @carrier = Carrier.find(params[:id])
    @carrier.destroy

    respond_to do |format|
      format.html { redirect_to carriers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  # GET /positions
  # GET /positions.json
  def index
    @positions = Position.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @positions }
    end
  end

  # GET /positions/1
  # GET /positions/1.json
  def show
    @position = Position.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @position }
    end
  end

  # GET /positions/new
  # GET /positions/new.json
  def new
    @position = Position.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @position }
    end
  end

  # GET /positions/1/edit
  def edit
    @position = Position.find(params[:id])
  end

  # POST /positions
  # POST /positions.json
  def create
    @position = Position.new(params[:position])

    respond_to do |format|
      if @position.save
        format.html { redirect_to @position, notice: 'Position was successfully created.' }
        format.json { render json: @position, status: :created, location: @position }
      else
        format.html { render action: "new" }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /positions/1
  # PUT /positions/1.json
  def update
    @position = Position.find(params[:id])

    respond_to do |format|
      if @position.update_attributes(params[:position])
        format.html { redirect_to @position, notice: 'Position was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /positions/1
  # DELETE /positions/1.json
  def destroy
    @position = Position.find(params[:id])
    @position.destroy

    respond_to do |format|
      format.html { redirect_to positions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carriers_helper.rb
module CarriersHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/carriers/_form.html.erb
<%= form_for(@carrier) do |f| %>
  <% if @carrier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@carrier.errors.count, "error") %> prohibited this carrier from being saved:</h2>

      <ul>
      <% @carrier.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :carrierType %><br />
    <%= f.number_field :carrierType %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carriers/edit.html.erb
<h1>Editing carrier</h1>

<%= render 'form' %>

<%= link_to 'Show', @carrier %> |
<%= link_to 'Back', carriers_path %>

app/views/carriers/index.html.erb
<h1>Listing carriers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Active</th>
    <th>Type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @carriers.each do |carrier| %>
  <tr>
    <td><%= carrier.name %></td>
    <td><%= carrier.active %></td>
    <td><%= carrier.carrierType %></td>
    <td><%= link_to 'Show', carrier %></td>
    <td><%= link_to 'Edit', edit_carrier_path(carrier) %></td>
    <td><%= link_to 'Destroy', carrier, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Carrier', new_carrier_path %>

app/views/carriers/new.html.erb
<h1>New carrier</h1>

<%= render 'form' %>

<%= link_to 'Back', carriers_path %>

app/views/carriers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @carrier.name %>
</p>

<p>
  <b>Active:</b>
  <%= @carrier.active %>
</p>

<p>
  <b>Type:</b>
  <%= @carrier.type %>
</p>


<%= link_to 'Edit', edit_carrier_path(@carrier) %> |
<%= link_to 'Back', carriers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bicecle</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/positions/_form.html.erb
<%= form_for(@position) do |f| %>
  <% if @position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@position.errors.count, "error") %> prohibited this position from being saved:</h2>

      <ul>
      <% @position.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :carrier_id %><br />
    <%= f.number_field :carrier_id %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/positions/edit.html.erb
<h1>Editing position</h1>

<%= render 'form' %>

<%= link_to 'Show', @position %> |
<%= link_to 'Back', positions_path %>

app/views/positions/index.html.erb
<h1>Listing positions</h1>

<table>
  <tr>
    <th>Carrier</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @positions.each do |position| %>
  <tr>
    <td><%= position.carrier_id %></td>
    <td><%= position.latitude %></td>
    <td><%= position.longitude %></td>
    <td><%= link_to 'Show', position %></td>
    <td><%= link_to 'Edit', edit_position_path(position) %></td>
    <td><%= link_to 'Destroy', position, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Position', new_position_path %>

app/views/positions/new.html.erb
<h1>New position</h1>

<%= render 'form' %>

<%= link_to 'Back', positions_path %>

app/views/positions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Carrier:</b>
  <%= @position.carrier_id %>
</p>

<p>
  <b>Latitude:</b>
  <%= @position.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @position.longitude %>
</p>


<%= link_to 'Edit', edit_position_path(@position) %> |
<%= link_to 'Back', positions_path %>